---
- name: install opp-extra
  hosts: opp_prod
  gather_facts: no
  vars_files:
    - vars/app_vars.yml
  tasks:
    - name: check nginx ssl crt exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "{{ software_src_path }}/{{ src_ssl_crt }}"
      register: ssl_crt_file
      run_once: true
      tags: apply_nginx_custom_ssl
    - name: copy nginx ssl crt
      ansible.builtin.copy:
        src: "{{ software_src_path }}/{{ src_ssl_crt }}"
        dest: "/opt/nginx/conf/ssl/{{ custom_hostname }}.crt"
        owner: nginx
        group: www-group
        mode: '0400'
      when: ssl_crt_file.stat.exists | default(false)
      tags: apply_nginx_custom_ssl
    - name: check nginx ssl key exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "{{ software_src_path }}/{{ src_ssl_key }}"
      register: ssl_key_file
      run_once: true
      tags: apply_nginx_custom_ssl
    - name: copy nginx ssl key
      ansible.builtin.copy:
        src: "{{ software_src_path }}/{{ src_ssl_key }}"
        dest: "/opt/nginx/conf/ssl/{{ custom_hostname }}.key"
        owner: nginx
        group: www-group
        mode: '0400'
      when: ssl_key_file.stat.exists | default(false)
      tags: apply_nginx_custom_ssl
    - name: edit ssl.conf ssl_certificate
      ansible.builtin.replace:
        path: /opt/nginx/conf/ssl/ssl.conf
        regexp: 'ssl_certificate /opt/nginx/conf/ssl/poxappprd52a.crt;'
        replace: 'ssl_certificate /opt/nginx/conf/ssl/{{ custom_hostname }}.crt;'
      tags: apply_nginx_custom_ssl
    - name: edit ssl.conf ssl_certificate_key
      ansible.builtin.replace:
        path: /opt/nginx/conf/ssl/ssl.conf
        regexp: 'ssl_certificate_key /opt/nginx/conf/ssl/poxappprd52a.key;'
        replace: 'ssl_certificate_key /opt/nginx/conf/ssl/{{ custom_hostname }}.key;'
      tags: apply_nginx_custom_ssl
    - name: nginx service ssl restart
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
      tags: apply_nginx_custom_ssl
  handlers:
      - name: reload systemd
        ansible.builtin.systemd:
          daemon_reload: yes
      - name: reload firewalld
        ansible.builtin.service:
          name: firewalld
          state: reloaded
      - name: restart chronyd
        ansible.builtin.service:
          name: chronyd
          state: restarted