---
- name: install opp-extra
  hosts: opp_prod_52:opp_prod_42
  gather_facts: no
  vars_files:
    - vars/app_vars.yml
  tasks:
    - name: check cert exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "{{ software_src_path }}/{{ src_ssl_crt }}"
      register: ssl_crt_file
      run_once: true
      tags: check_cert_exists
    - name: copy nginx ssl crt
      ansible.builtin.copy:
        src: "{{ software_src_path }}/{{ src_ssl_crt }}"
        dest: "/opt/nginx/conf/ssl/{{ custom_hostname }}.crt"
        owner: nginx
        group: www-group
        mode: '0400'
      when: ssl_crt_file.stat.exists | default(false)
      tags: apply_nginx_custom_ssl
    - name: check key exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: "{{ software_src_path }}/{{ src_ssl_key }}"
      register: ssl_key_file
      run_once: true
      tags: check_key_exists
    - name: copy nginx ssl key
      ansible.builtin.copy:
        src: "{{ software_src_path }}/{{ src_ssl_key }}"
        dest: "/opt/nginx/conf/ssl/{{ custom_hostname }}.key"
        owner: nginx
        group: www-group
        mode: '0400'
      when: ssl_key_file.stat.exists | default(false)
      tags: apply_nginx_custom_ssl
    - name: edit ssl.conf ssl_certificate
      ansible.builtin.replace:
        path: /opt/nginx/conf/ssl/ssl.conf
        regexp: 'ssl_certificate /opt/nginx/conf/ssl/poxappprd52a.crt;'
        replace: 'ssl_certificate /opt/nginx/conf/ssl/{{ custom_hostname }}.crt;'
      tags: apply_nginx_custom_ssl
    - name: edit ssl.conf ssl_certificate_key
      ansible.builtin.replace:
        path: /opt/nginx/conf/ssl/ssl.conf
        regexp: 'ssl_certificate_key /opt/nginx/conf/ssl/poxappprd52a.key;'
        replace: 'ssl_certificate_key /opt/nginx/conf/ssl/{{ custom_hostname }}.key;'
      tags: apply_nginx_custom_ssl
    - name: nginx service ssl restart
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
      tags: apply_nginx_custom_ssl
    - name: config ldap cert
      tags: config_ldap_cert
      block:
        - name: copy ldap cert
          ansible.builtin.copy:
            src: "{{ software_src_path }}/{{ src_ssl_crt }}"
            dest: "/etc/pki/ca-trust/source/anchors/"
          when: ssl_crt_file.stat.exists | default(false)            
        - name: edit ldap cert
          blockinfile:
            path: /etc/openldap/ldap.conf
            block: |
              TLS_CACERTDIR /etc/pki/ca-trust/source/anchors
              TLS_REQCERT never
              TLS_CRLCHECK none

              URI ldaps://corprodc03.corp.ha.org.hk:636
              BASE dc=corp,dc=ha,dc=org,dc=hk
            marker: "#### {mark} ADDED BY OPP INSTALLATION ####"
            backup: yes
            state: present